Repository DDD-Community/DDD11-SClass-iOS, pull requests merged in 2024-09, with the labels that each got.

#23 #17 - 채팅 플로우 구현
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/InfoPlist/InfoPlistDictionary.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/InfoPlist/Project+InfoPlist.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/Project+Templete/Project+Enviorment.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/Setting/Project+Settings.swift
  Projects/App/Entitlements/OnboardingKit.entitlements
  Projects/Core/Domain/Sources/Models/ChatSession.swift
  Projects/Core/Domain/Sources/Models/CheckBox.swift
  Projects/Core/Domain/Sources/Models/CheckList.swift
  Projects/Core/Domain/Sources/Models/CheckListExampleEntity.swift
  Projects/Core/Domain/Sources/Models/Message.swift
  Projects/Core/Network/Sources/Infrastructure/Foundation/APIService.swift
  Projects/Core/Network/Sources/Infrastructure/Foundation/BaseAPI.swift
  Projects/Core/Network/Sources/Services/Chat/ChatAPI.swift
  Projects/Core/Network/Sources/Services/Chat/ChatAPIClient.swift
  Projects/Core/Network/Sources/Services/Chat/Request/SendMessageRequestDTO.swift
  Projects/Core/Network/Sources/Services/Chat/Response/CreateSessionResponseDTO.swift
  Projects/Core/Network/Sources/Services/Chat/Response/MessageResponseDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/CheckListAPI.swift
  Projects/Core/Network/Sources/Services/CheckList/CheckListAPIClient.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/CheckListDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/CheckListItemDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/DeleteCheckListResponseDTO.swift
  Projects/Core/Network/Sources/Services/KeyChain/KeychainClient.swift
  Projects/Feature/Chat/Sources/Chat/ChatNavigationStore.swift
  Projects/Feature/Chat/Sources/Chat/ChatStore.swift
  Projects/Feature/Chat/Sources/Chat/ChatView.swift
  Projects/Feature/Chat/Sources/ChatStore.swift
  Projects/Feature/Chat/Sources/ChatView.swift
  Projects/Feature/Chat/Sources/CreateCheckList/CreateCheckListStore.swift
  Projects/Feature/Chat/Sources/CreateCheckList/CreateCheckListView.swift
  Projects/Feature/Chat/Sources/EnterKeyword/EnterKeywordStore.swift
  Projects/Feature/Chat/Sources/EnterKeyword/EnterKeywordView.swift
  Projects/Feature/Chat/Sources/Entity/CheckListEntity.swift
  Projects/Feature/Chat/Sources/Entity/MessageEntity.swift
  Projects/Feature/Sources/MainTab/MainTabStore.swift
  Projects/Feature/Sources/MainTab/MainTabView.swift
  Projects/Shared/DesignSystem/Resources/Image.xcassets/chatPlaceholder.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/chatPlaceholder.imageset/chatPlacheHolder.pdf
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/CheckBoxButton.swift
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/DefaultChecklistCellView.swift
  Projects/Shared/DesignSystem/Sources/Components/Modal/HistoryAlertView.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: ✨ 기능추가, 🎨 디자인, ⚙️ 환경설정

#24 #22 - 홈 UI 구현 및 아티클 API 연동
  Plugins/DependencyPackagePlugin/ProjectDescriptionHelpers/TargetDependency+Module/Extension+TargetDependencySPM.swift
  Projects/Core/Domain/Sources/Models/Article.swift
  Projects/Core/Network/Sources/Infrastructure/Foundation/BaseAPI.swift
  Projects/Core/Network/Sources/Services/Home/HomeAPI.swift
  Projects/Core/Network/Sources/Services/Home/HomeAPIClient.swift
  Projects/Core/Network/Sources/Services/Home/Response/ArticleResponseDTO.swift
  Projects/Core/Network/Sources/Services/Home/Response/ArticlesResponseDTO.swift
  Projects/Feature/Home/Sources/Home/HomeStore.swift
  Projects/Feature/Home/Sources/Home/HomeView.swift
  Projects/Feature/Home/Sources/Home/Views/ListSection.swift
  Projects/Feature/Home/Sources/Home/Views/ThumbnailImage.swift
  Projects/Feature/Home/Sources/HomeRootStore.swift
  Projects/Feature/Home/Sources/HomeRootView.swift
  Projects/Feature/Sources/MainTab/MainTabItem.swift
  Projects/Feature/Sources/MainTab/MainTabStore.swift
  Projects/Feature/Sources/MainTab/MainTabView.swift
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/HomeBackground.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/HomeBackground.imageset/HomeBackground@1x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/HomeBackground.imageset/HomeBackground@2x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/HomeBackground.imageset/HomeBackground@3x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/append_folder.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/append_folder.imageset/append_folder@1x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/append_folder.imageset/append_folder@2x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Home/append_folder.imageset/append_folder@3x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/TabView/plus.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/TabView/plus.imageset/plus@1x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/TabView/plus.imageset/plus@2x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/TabView/plus.imageset/plus@3x.png
  Projects/Shared/DesignSystem/Sources/Cells/Article/ArticleCellView.swift
  Projects/Shared/DesignSystem/Sources/Components/TabView/TabBarItemCircleView.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
  Projects/Shared/ThirdPartyLib/Project.swift
  Projects/Shared/Utils/Sources/Foundation/Date+.swift
  Tuist/Package.swift
Labels: ✨ 기능추가, 🎨 디자인

#26 [Setting] #25 - fastlane 기본 파일 설정
  fastlane/.env
  fastlane/Appfile
  fastlane/Matchfile
Labels: ⚙️ 환경설정

#29 #28 - 0.0.1 testflight 릴리즈 준비
  .gitignore
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/InfoPlist/InfoPlistDictionary.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/InfoPlist/Project+InfoPlist.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/Project+Templete/Project+Enviorment.swift
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/Setting/Project+Settings.swift
  Projects/Core/Domain/Sources/Models/Article.swift
  Projects/Core/Network/Sources/Infrastructure/Foundation/NetworkEnvironment.swift
  Projects/Core/Network/Sources/Services/Chat/ChatAPI.swift
  fastlane/Matchfile
Labels: ⚙️ 환경설정, 🚀 배포

#31 #30 - 홈 아티클 클릭 시 웹뷰로 이동 구현
  Projects/Core/Domain/Sources/Models/Article.swift
  Projects/Feature/Home/Sources/Home/Article/HomeArticleWebView.swift
  Projects/Feature/Home/Sources/Home/HomeStore.swift
  Projects/Feature/Home/Sources/Home/HomeView.swift
  Projects/Feature/Home/Sources/Home/Views/HomeArticleWebView.swift
  Projects/Shared/DesignSystem/Sources/Cells/Article/ArticleCellView.swift
  Projects/Shared/DesignSystem/Sources/Components/Navigation/TopArticleNavigation.swift
  Projects/Shared/DesignSystem/Sources/Components/WebViewRepresentable.swift
Labels: ✨ 기능추가

#32 #27 - 홈 체크리스트 관련된 UI 및 API 연동 작업
  Plugins/DependencyPackagePlugin/ProjectDescriptionHelpers/TargetDependency+Module/Extension+TargetDependencySPM.swift
  Projects/Core/Common/Sources/Skeleton/SkeletonRectangleView.swift
  Projects/Core/Common/Sources/Skeleton/SkeletonRoundedView.swift
  Projects/Core/Domain/Sources/Models/CheckBox.swift
  Projects/Core/Domain/Sources/Models/CheckList.swift
  Projects/Core/Domain/Sources/Models/Checklist.swift
  Projects/Core/Domain/Sources/Models/ChecklistExampleEntity.swift
  Projects/Core/Network/Sources/Infrastructure/Foundation/BaseAPI.swift
  Projects/Core/Network/Sources/Services/CheckList/CheckListAPI.swift
  Projects/Core/Network/Sources/Services/CheckList/CheckListAPIClient.swift
  Projects/Core/Network/Sources/Services/CheckList/ChecklistAPI.swift
  Projects/Core/Network/Sources/Services/CheckList/ChecklistAPIClient.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/CheckListDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/ChecklistItemDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/ChecklistResponseDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/ChecklistsResponseDTO.swift
  Projects/Core/Network/Sources/Services/CheckList/Response/DeleteChecklistResponseDTO.swift
  Projects/Feature/Chat/Sources/Chat/ChatNavigationStore.swift
  Projects/Feature/Chat/Sources/Chat/ChatStore.swift
  Projects/Feature/Chat/Sources/Chat/ChatView.swift
  Projects/Feature/Chat/Sources/CreateCheckList/CreateCheckListStore.swift
  Projects/Feature/Chat/Sources/CreateChecklist/CreateChecklistStore.swift
  Projects/Feature/Chat/Sources/CreateChecklist/CreateChecklistView.swift
  Projects/Feature/Chat/Sources/EnterKeyword/EnterKeywordStore.swift
  Projects/Feature/Chat/Sources/Entity/ChecklistEntity.swift
  Projects/Feature/Home/Sources/Home/Article/HomeArticleWebView.swift
  Projects/Feature/Home/Sources/Home/CardModel.swift
  Projects/Feature/Home/Sources/Home/HomeStore.swift
  Projects/Feature/Home/Sources/Home/HomeView.swift
  Projects/Feature/Home/Sources/Home/Views/HeaderView.swift
  Projects/Feature/Home/Sources/Home/Views/HomeArticleWebView.swift
  Projects/Feature/Home/Sources/Home/Views/HomeCardView.swift
  Projects/Feature/Home/Sources/Home/Views/ProgressView.swift
  Projects/Feature/Home/Sources/Home/Views/SkeletonView/SkeletonContentView.swift
  Projects/Feature/Home/Sources/Home/Views/SkeletonView/SkeletonHeaderView.swift
  Projects/Feature/Home/Sources/HomeRootStore.swift
  Projects/Feature/Sources/MainTab/MainTabStore.swift
  Projects/Shared/DesignSystem/Sources/Cells/Article/ArticleCellView.swift
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/ColorCheckBoxButton.swift
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/ColorChecklistCellView.swift
  Projects/Shared/ThirdPartyLib/Project.swift
  Tuist/Package.swift
Labels: ♻️ 리팩토링, ✨ 기능추가, 🎨 디자인

#34 [Release] v0.1.0 배포
  Plugins/ProjectTemplatePlugin/ProjectDescriptionHelpers/Project+Templete/Project+Enviorment.swift
  Projects/Feature/Chat/Sources/CreateChecklist/CreateChecklistStore.swift
  Projects/Feature/Chat/Sources/EnterKeyword/EnterKeywordStore.swift
  Projects/Feature/Home/Sources/Home/HomeView.swift
  Projects/Shared/DesignSystem/Sources/Cells/Article/ArticleCellView.swift
Labels: ⚙️ 환경설정, 🚀 배포
