Repository DDD-Community/DDD11-SClass-iOS, pull requests merged in 2024-08, with the labels that each got.

#6 [Feat] #5 - Font와 LineHeight를 함께 적용할 수 있는 ViewModifier 추가
  Projects/Shared/DesignSystem/Sources/Colors.swift
  Projects/Shared/DesignSystem/Sources/Extensions/View+notoSans.swift
  Projects/Shared/DesignSystem/Sources/Font.swift
Labels: ✨ 기능추가, 🎨 디자인

#14 #13 - 기록, 아티클 탭 EmptyView 추가
  Projects/Feature/Article/Sources/ArticleView.swift
  Projects/Feature/History/Sources/HistoryView.swift
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Article/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Article/articleEmptyView.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Article/articleEmptyView.imageset/articleEmptyView@1x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Article/articleEmptyView.imageset/articleEmptyView@2x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/Article/articleEmptyView.imageset/articleEmptyView@3x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/History/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/History/historyEmptyView.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/History/historyEmptyView.imageset/historyEmptyView@1x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/History/historyEmptyView.imageset/historyEmptyView@2x.png
  Projects/Shared/DesignSystem/Resources/Image.xcassets/History/historyEmptyView.imageset/historyEmptyView@3x.png
  Projects/Shared/DesignSystem/Sources/Colors.swift
  Projects/Shared/DesignSystem/Sources/Components/Buttons/ButtonSmall.swift
  Projects/Shared/DesignSystem/Sources/Components/Buttons/CommonButton.swift
  Projects/Shared/DesignSystem/Sources/Components/Chip/Chip.swift
  Projects/Shared/DesignSystem/Sources/Components/Input/InputField.swift
  Projects/Shared/DesignSystem/Sources/Components/Navigation/TopArticleNavigation.swift
  Projects/Shared/DesignSystem/Sources/Components/Navigation/TopNavigation.swift
  Projects/Shared/DesignSystem/Sources/Components/ProgressBar/CommonProgressBar.swift
  Projects/Shared/DesignSystem/Sources/Components/TabView/TabBarItemCircleView.swift
  Projects/Shared/DesignSystem/Sources/Components/Text/ColoredText.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: 🎨 디자인, 🔧 기타수정

#15 #12 - 나머지 컴포넌트 구현
  Projects/Shared/DesignSystem/Resources/Image.xcassets/CheckList/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/CheckList/check.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/CheckList/check.imageset/check.pdf
  Projects/Shared/DesignSystem/Resources/Image.xcassets/right.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/right.imageset/right.pdf
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/CheckBoxButton.swift
  Projects/Shared/DesignSystem/Sources/Cells/Checklist/DefaultChecklistCellView.swift
  Projects/Shared/DesignSystem/Sources/Cells/MyPage/MyPageCellView.swift
  Projects/Shared/DesignSystem/Sources/Components/Modal/HistoryAlertView.swift
  Projects/Shared/DesignSystem/Sources/Extensions/View+historyAlert.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: 🎨 디자인

#16 #11 - 채팅 컴포넌트 구현
  Projects/Shared/DesignSystem/Resources/Image.xcassets/chatbot.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/chatbot.imageset/chatbot.pdf
  Projects/Shared/DesignSystem/Resources/Image.xcassets/send_active.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image.xcassets/send_active.imageset/Property 1=True.pdf
  Projects/Shared/DesignSystem/Resources/Image.xcassets/send_deactive.imageset/Arrow_alt_lright.pdf
  Projects/Shared/DesignSystem/Resources/Image.xcassets/send_deactive.imageset/Contents.json
  Projects/Shared/DesignSystem/Sources/Components/Buttons/ButtonSmall.swift
  Projects/Shared/DesignSystem/Sources/Components/Buttons/PressedButtonStyle.swift
  Projects/Shared/DesignSystem/Sources/Components/Chat/ChatInputView.swift
  Projects/Shared/DesignSystem/Sources/Components/Chat/MessageBubbleView.swift
  Projects/Shared/DesignSystem/Sources/Components/Chat/PromptExampleView.swift
  Projects/Shared/DesignSystem/Sources/Images.swift
Labels: 🎨 디자인
